# Site settings
title: Jiajun Zhang
tagline:          'Homepage'
description:      'Cosmology, N-body Simulation'
email: liamzhang at sjtu.edu.cn
#description: > # this means to ignore newlines until "baseurl:"
#  Thank you for visiting my website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  liambx

# Build settings
markdown: kramdown
maruku:
  use_tex:    true

